name := "qutebrowser"
packages := "
qutebrowser
python3-adblock
"
base_images := "
quay.io/fedora-ostree-desktops/base-atomic:41 x86_64
quay.io/fedora-ostree-desktops/base-atomic:42 x86_64
"
copr_repos := "ismaelpuerto/python-adblock"

import '../sysext.just'

all: default
