name := "arm-image-installer"
packages := "
arm-image-installer
parted
"
base_images := "
quay.io/fedora-ostree-desktops/base-atomic:41 x86_64,aarch64
quay.io/fedora-ostree-desktops/base-atomic:42 x86_64,aarch64
quay.io/fedora-ostree-desktops/base-atomic:43 x86_64,aarch64
"

import '../sysext.just'

all: default

