name := "cri-o-1.32"
packages := "
cri-o1.32
cri-tools1.32
"
exclude_packages := "
cri-tools
"
base_images := "
quay.io/fedora/fedora-coreos:stable x86_64,aarch64
"

import '../sysext.just'

all: default
