name := "kubernetes-cri-o-1.31"
packages := "
cri-o1.31
cri-tools1.31
kubernetes1.31
kubernetes1.31-client
kubernetes1.31-kubeadm
"
exclude_packages := "
cri-tools
"
base_images := "
quay.io/fedora/fedora-coreos:stable x86_64,aarch64
"

import '../sysext.just'

all: default
