name := "bitwarden"
packages := "bitwarden"
pre_commands := "rm -rf /opt; mkdir /opt"
base_images := "
quay.io/fedora-ostree-desktops/silverblue:41
quay.io/fedora-ostree-desktops/silverblue:42
quay.io/fedora-ostree-desktops/kinoite:41
quay.io/fedora-ostree-desktops/kinoite:42
"

import '../sysext.just'

all: default

download-manual arch=arch:
    #!/bin/bash
    set -euo pipefail
    # set -x

    mkdir -p rpms
    curl -Lo rpms/bitwarden.rpm \
        "https://bitwarden.com/download/?app=desktop&platform=linux&variant=rpm"

install-manual:
    #!/bin/bash
    set -euo pipefail
    # set -x

    if [[ "${UID}" == "0" ]]; then
        SUDO=""
    else
        SUDO="sudo"
    fi

    cd rootfs

    ${SUDO} mv opt/Bitwarden usr/lib/Bitwarden
    ${SUDO} rmdir opt
    ${SUDO} mkdir usr/bin
    ${SUDO} ln -sf /usr/lib/Bitwarden/bitwarden usr/bin/bitwarden
    ${SUDO} ln -sf /usr/lib/Bitwarden/bitwarden-app usr/bin/bitwarden-app
    ${SUDO} chmod 4755 usr/lib/Bitwarden/chrome-sandbox
    ${SUDO} sed -i 's|^Exec=/opt/Bitwarden|Exec=/usr/bin|g' usr/share/applications/bitwarden.desktop
