name := "kubernetes-1.31"
packages := "
cri-tools1.31
kubernetes1.31
kubernetes1.31-client
kubernetes1.31-kubeadm
"
exclude_packages := "
cri-tools
"
base_images := "
quay.io/fedora/fedora-coreos:stable x86_64,aarch64
"

import '../sysext.just'

all: default

# Setup folder that is expected by Kubernetes
install-manual:
    #!/bin/bash
    set -euo pipefail
    # set -x
    if [[ "${UID}" == "0" ]]; then
        SUDO=""
    else
        SUDO="sudo"
    fi
    cd rootfs
    ${SUDO} install -d -m 755 -o 0 -g 0 usr/libexec/kubernetes/kubelet-plugins/volume/exec
