name := "krb5-workstation"
packages := "krb5-workstation"
base_images := "
quay.io/fedora-ostree-desktops/silverblue:41
quay.io/fedora-ostree-desktops/silverblue:42
quay.io/fedora-ostree-desktops/kinoite:41
quay.io/fedora-ostree-desktops/kinoite:42
"

import '../sysext.just'

all: default
