name := "vagrant"
packages := "vagrant"
external_repos := "https://rpm.releases.hashicorp.com/fedora/hashicorp.repo"
disable_repos := "fedora updates updates-archive"
base_images := "
quay.io/fedora-ostree-desktops/base-atomic:41 x86_64
quay.io/fedora-ostree-desktops/base-atomic:42 x86_64
"

import '../sysext.just'

all: default

install-manual:
    #!/bin/bash
    set -euo pipefail
    set -x

    if [[ "${UID}" == "0" ]]; then
        SUDO=""
    else
        SUDO="sudo"
    fi

    cd rootfs

    ${SUDO} mv ./opt/vagrant ./usr/lib/vagrant
