name := "gdb"
packages := "gdb"
cleanup_files := "/var/lib/unbound/root.key"
base_images := "
quay.io/fedora/fedora-coreos:stable x86_64,aarch64
quay.io/fedora/fedora-coreos:next x86_64,aarch64
"

import '../sysext.just'

all: default
