FROM baseimage

RUN dnf install -y \
    --enablerepo="updates-testing" \
    --exclude cri-tools \
    cri-tools1.32 \
    kubernetes1.32 \
    kubernetes1.32-client \
    kubernetes1.32-kubeadm \
    kubernetes1.32-systemd \
    && \
    dnf clean all
