name := "kubernetes-1.32"
packages := "
cri-tools1.32
kubernetes1.32
kubernetes1.32-client
kubernetes1.32-kubeadm
kubernetes1.32-systemd
"
exclude_packages := "
cri-tools
"
# https://bodhi.fedoraproject.org/updates/FEDORA-2024-7865310e27
# https://bodhi.fedoraproject.org/updates/FEDORA-2024-bc020f9b2d
enable_repos := "updates-testing"
base_images := "
quay.io/fedora/fedora-coreos:stable x86_64,aarch64
"

import '../sysext.just'

all: default
