FROM baseimage

ARG VERSION=1.33

RUN <<EORUN
set -xeuo pipefail
dnf install -y \
    --exclude cri-tools \
    cri-o${VERSION} \
    cri-tools${VERSION} \
    kubernetes${VERSION} \
    kubernetes${VERSION}-client \
    kubernetes${VERSION}-kubeadm
dnf clean all
EORUN
