name := "kubernetes-cri-o-1.29"
packages := "
cri-o1.29
cri-tools1.29
kubernetes1.29
kubernetes1.29-client
kubernetes1.29-kubeadm
"
exclude_packages := "
cri-tools
"
base_images := "
quay.io/fedora/fedora-coreos:stable x86_64,aarch64
"

import '../sysext.just'

all: default
