FROM baseimage

RUN dnf install -y dnf5-plugins \
    && \
    dnf config-manager addrepo --from-repofile="https://download.docker.com/linux/fedora/docker-ce.repo" \
    && \
    dnf install -y \
    docker-ce \
    docker-ce-cli \
    containerd.io \
    docker-buildx-plugin \
    docker-compose-plugin \
    && \
    dnf clean all
