name := "docker-ce"
packages := "
docker-ce
docker-ce-cli
containerd.io
docker-buildx-plugin
docker-compose-plugin
"
external_repos := "https://download.docker.com/linux/fedora/docker-ce.repo"
base_images := "
quay.io/travier/fedora-coreos:latest
"

import '../sysext.just'

all: default
