name := "docker-ce"
packages := "
docker-ce
docker-ce-cli
containerd.io
docker-buildx-plugin
docker-compose-plugin
"
upholds := "
docker.socket
"
external_repos := "https://download.docker.com/linux/fedora/docker-ce.repo"
base_images := "
quay.io/fedora-ostree-desktops/base-atomic:41 x86_64,aarch64
quay.io/fedora-ostree-desktops/base-atomic:42 x86_64,aarch64
"

import '../sysext.just'

all: default
