name := "openh264"
packages := "
mozilla-openh264
openh264
"
enable_repos := "fedora-cisco-openh264"
base_images := "
quay.io/fedora-ostree-desktops/silverblue:41
quay.io/fedora-ostree-desktops/kinoite:41
"

import '../sysext.just'

all: default
