name := "steam-devices"
packages := "steam-devices"
enable_repos := "rpmfusion-nonfree-steam"
dnf_arch := "i686"
base_images := "
quay.io/fedora-ostree-desktops/silverblue:41
quay.io/fedora-ostree-desktops/kinoite:41
"

import '../sysext.just'

all: default
