name := "amazon-ec2-utils"
packages := "
amazon-ec2-utils
awscli2
ec2-instance-connect
"
base_images := "
quay.io/fedora/fedora-coreos:stable x86_64,aarch64
quay.io/fedora/fedora-coreos:next x86_64,aarch64
"

import '../sysext.just'

all: default
