name := "openconnect"
packages := "openconnect"
copr_repos := "dwmw2/openconnect"
version_package := "openconnect"
base_images := "
quay.io/fedora-ostree-desktops/base-atomic:41 x86_64
quay.io/fedora-ostree-desktops/base-atomic:42 x86_64
"

import '../sysext.just'

all: default
