name := "lact"
packages := "
lact
"
base_images := "
quay.io/fedora-ostree-desktops/kinoite:41
"
copr_repos := "ilyaz/LACT"
disable_repos := "'*'"
enable_repos := "copr:copr.fedorainfracloud.org:ilyaz:LACT"


import '../sysext.just'

all: default
