name := "steam-kinoite"
packages := "
gamescope
mangohud
steam
"
version_package := "steam"
rpm_fusion_repos := "free nonfree"
dnf_arch := "noarch i686 x86_64"
base_images := "
"
# quay.io/fedora-ostree-desktops/kinoite:41 x86_64
# quay.io/fedora-ostree-desktops/kinoite:42 x86_64

import '../sysext.just'

all: default

install-manual:
    #!/bin/bash
    set -euo pipefail
    if [[ -n "{{debug}}" ]]; then
      set -x
    fi

    if [[ "${UID}" == "0" ]]; then
        SUDO=""
    else
        SUDO="sudo"
    fi

    cd rootfs

    # Merge /lib with /usr/lib
    ${SUDO} mv ./lib/* ./usr/lib
    ${SUDO} rmdir ./lib
