name := "brave"
packages := "brave-browser"
base_images := "
quay.io/fedora-ostree-desktops/base-atomic:41 x86_64,aarch64
quay.io/fedora-ostree-desktops/base-atomic:42 x86_64,aarch64
"
external_repos := "https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo"

import '../sysext.just'

all: default

install-manual:
    #!/bin/bash
    set -euo pipefail
    if [[ -n "{{debug}}" ]]; then
        set -x
    fi

    if [[ "${UID}" == "0" ]]; then
        SUDO=""
    else
        SUDO="sudo"
    fi

    cd rootfs

    ${SUDO} mv opt/brave.com usr/lib/
    ${SUDO} rmdir opt
    ${SUDO} ln -sf /usr/lib/brave.com/brave/brave-browser usr/bin/brave-browser-stable
    ${SUDO} rm -rf etc
