FROM baseimage

RUN dnf install -y \
    --exclude cri-tools \
    cri-o1.30 \
    cri-tools1.30 \
    kubernetes1.30 \
    kubernetes1.30-client \
    kubernetes1.30-kubeadm \
    kubernetes1.30-systemd \
    && \
    dnf clean all
