name := "kubernetes-cri-o-1.30"
packages := "
cri-o1.30
cri-tools1.30
kubernetes1.30
kubernetes1.30-client
kubernetes1.30-kubeadm
"
exclude_packages := "
cri-tools
"
base_images := "
quay.io/fedora/fedora-coreos:stable x86_64,aarch64
"

import '../sysext.just'

all: default
