kube_version := "1.30"
name := "kubernetes-cri-o-" + kube_version
packages := "
cri-o"      + kube_version + "
cri-tools"  + kube_version + "
kubernetes" + kube_version + "
kubernetes" + kube_version + "-client
kubernetes" + kube_version + "-kubeadm
"
exclude_packages := "
cri-o
cri-tools
"
upholds := "
crio.service
kubelet.service
"
version_package := "kubernetes" + kube_version
base_images := "
quay.io/fedora/fedora-coreos:stable x86_64,aarch64
quay.io/fedora/fedora-coreos:next x86_64,aarch64
"

import '../sysext.just'

all: default

install-manual:
    #!/bin/bash
    set -euo pipefail
    # set -x
    if [[ "${UID}" == "0" ]]; then
        SUDO=""
    else
        SUDO="sudo"
    fi
    cd rootfs

    # Setup folder that is expected by Kubernetes
    ${SUDO} install -d -m 755 -o 0 -g 0 usr/libexec/kubernetes/kubelet-plugins/volume/exec

    # Ignore folder in /var
    ${SUDO} rmdir var/lib/containers
    ${SUDO} rmdir var/lib/kubelet var/lib var
