name := "steam"
packages := "steam"
enable_repos := "rpmfusion-nonfree-steam"
arch := "noarch i686 x86_64"
base_images := "quay.io/fedora-ostree-desktops/kinoite:41"

import '../sysext.just'

default target: (all target)
