name := "steam"
packages := "
gamescope
mangohud
steam
"
enable_repos := "rpmfusion-nonfree-steam"
dnf_arch := "noarch i686 x86_64"
base_images := "
quay.io/fedora-ostree-desktops/silverblue:41
quay.io/fedora-ostree-desktops/silverblue:42
quay.io/fedora-ostree-desktops/kinoite:41
quay.io/fedora-ostree-desktops/kinoite:42
"

import '../sysext.just'

all: default
