name := "swtpm"
packages := "
checkpolicy
libb2
libgomp
libtpms
mpdecimal
policycoreutils-python-utils
python-pip-wheel
python-unversioned-command
python3
python3-audit
python3-distro
python3-libs
python3-libselinux
python3-libsemanage
python3-policycoreutils
python3-setools
python3-setuptools
swtpm
swtpm-libs
swtpm-selinux
"
base_images := "
quay.io/fedora/fedora-coreos:next
quay.io/fedora-ostree-desktops/kinoite:41
"

import '../sysext.just'

all: default
