name := "kubernetes-cri-o-1.32"
packages := "
cri-o1.32
cri-tools1.32
kubernetes1.32
kubernetes1.32-client
kubernetes1.32-kubeadm
"
exclude_packages := "
cri-tools
"
base_images := "
quay.io/fedora/fedora-coreos:stable x86_64,aarch64
"

import '../sysext.just'

all: default
