name := "kubernetes-1.29"
packages := "
kubernetes1.29
kubernetes1.29-client
kubernetes1.29-kubeadm
kubernetes1.29-systemd
"
base_images := "
quay.io/fedora/fedora-coreos:stable x86_64,aarch64
"

import '../sysext.just'

all: default
