FROM baseimage

RUN dnf install -y \
    guestfs-tools \
    libguestfs \
    libguestfs-xfs \
    libvirt-client \
    libvirt-daemon \
    libvirt-daemon-config-network \
    libvirt-daemon-driver-interface \
    libvirt-daemon-driver-network \
    libvirt-daemon-driver-nodedev \
    libvirt-daemon-driver-nwfilter \
    libvirt-daemon-driver-qemu \
    libvirt-daemon-driver-secret \
    libvirt-daemon-driver-storage-core \
    libvirt-dbus \
    netcat \
    qemu \
    qemu-img \
    swtpm \
    virt-install \
    && \
    dnf clean all
