name := "libvirtd-desktop"
packages := "
guestfs-tools
libguestfs
libguestfs-xfs
libosinfo
libvirt-client
libvirt-daemon
libvirt-daemon-config-network
libvirt-daemon-driver-interface
libvirt-daemon-driver-network
libvirt-daemon-driver-nodedev
libvirt-daemon-driver-nwfilter
libvirt-daemon-driver-qemu
libvirt-daemon-driver-secret
libvirt-daemon-driver-storage-core
libvirt-dbus
osinfo-db
osinfo-db-tools
netcat
qemu-kvm
qemu-img
swtpm
virt-install
"
upholds := "
virtlockd-admin.socket
virtlockd.socket
virtlogd-admin.socket
virtlogd.socket
virtnetworkd-admin.socket
virtnetworkd-ro.socket
virtnetworkd.socket
virtqemud-admin.socket
virtqemud-ro.socket
virtqemud.socket
virtstoraged-admin.socket
virtstoraged-ro.socket
virtstoraged.socket
"
version_package := "libvirt-client"
base_images := "
quay.io/fedora-ostree-desktops/base-atomic:41 x86_64,aarch64
quay.io/fedora-ostree-desktops/base-atomic:42 x86_64,aarch64
"

import '../sysext.just'

all: default

install-manual:
    #!/bin/bash
    set -euo pipefail
    if [[ -n "{{debug}}" ]]; then
      set -x
    fi

    if [[ "${UID}" == "0" ]]; then
        SUDO=""
    else
        SUDO="sudo"
    fi

    cd rootfs

    # Fixup netcat/nc as we don't run the alternatives command from scriplets
    ${SUDO} ln -snf netcat usr/bin/nc

    # Move extlinux to /usr/bin as needed
    if [[ -f sbin/extlinux ]]; then
        ${SUDO} mv sbin/extlinux usr/bin/extlinux
        ${SUDO} rmdir sbin
    fi

    # Empty out /var & /boot
    ${SUDO} rm -rf ./var ./boot
