name := "libvirtd-desktop"
packages := "
guestfs-tools
libguestfs
libguestfs-xfs
libvirt-client
libvirt-daemon
libvirt-daemon-config-network
libvirt-daemon-driver-interface
libvirt-daemon-driver-network
libvirt-daemon-driver-nodedev
libvirt-daemon-driver-nwfilter
libvirt-daemon-driver-qemu
libvirt-daemon-driver-secret
libvirt-daemon-driver-storage-core
libvirt-dbus
netcat
qemu
qemu-img
swtpm
virt-install
"
upholds := "
virtinterfaced-admin.socket
virtinterfaced-ro.socket
virtinterfaced.socket
virtlockd-admin.socket
virtlockd.socket
virtlogd-admin.socket
virtlogd.socket
virtnetworkd-admin.socket
virtnetworkd-ro.socket
virtnetworkd.socket
virtnodedevd-admin.socket
virtnodedevd-ro.socket
virtnodedevd.socket
virtnwfilterd-admin.socket
virtnwfilterd-ro.socket
virtnwfilterd.socket
virtqemud-admin.socket
virtqemud-ro.socket
virtqemud.socket
virtstoraged-admin.socket
virtstoraged-ro.socket
virtstoraged.socket
"
base_images := "
quay.io/fedora-ostree-desktops/silverblue:41
quay.io/fedora-ostree-desktops/silverblue:42
quay.io/fedora-ostree-desktops/kinoite:41
quay.io/fedora-ostree-desktops/kinoite:42
"

import '../sysext.just'

all: default

# Fixup netcat/nc as we don't run the alternatives command from scriplets
install-manual:
    #!/bin/bash
    set -euo pipefail
    # set -x

    if [[ "${UID}" == "0" ]]; then
        SUDO=""
    else
        SUDO="sudo"
    fi

    cd rootfs

    ${SUDO} ln -snf netcat usr/bin/nc
