name := "inxi"
packages := "inxi"
base_images := "
quay.io/fedora-ostree-desktops/base-atomic:41 x86_64,aarch64
quay.io/fedora-ostree-desktops/base-atomic:42 x86_64,aarch64
"

import '../sysext.just'

all: default

install-manual:
    #!/bin/bash
    set -euo pipefail
    # set -x

    if [[ "${UID}" == "0" ]]; then
        SUDO=""
    else
        SUDO="sudo"
    fi

    cd rootfs

    # Empty out /var
    ${SUDO} rm ./var/lib/freeipmi/ipckey
    ${SUDO} rmdir \
        ./var/cache/ipmimonitoringsdrcache \
        ./var/cache \
        ./var/lib/freeipmi \
        ./var/lib \
        ./var
