name := "google-chrome"
packages := "google-chrome-stable"
enable_repos := "google-chrome"
pre_commands := "rm -rf /opt && mkdir /opt"
base_images := "
quay.io/fedora-ostree-desktops/silverblue:41
quay.io/fedora-ostree-desktops/kinoite:41
"

import '../sysext.just'

all: default

install-manual:
    #!/bin/bash
    set -euo pipefail
    # set -x

    if [[ "${UID}" == "0" ]]; then
        SUDO=""
    else
        SUDO="sudo"
    fi

    cd rootfs

    ${SUDO} mv opt/google/chrome usr/lib/google-chrome
    ${SUDO} rmdir opt/{google,}
    ${SUDO} ln -sf /usr/lib/google-chrome/google-chrome usr/bin/google-chrome-stable
    ${SUDO} mkdir -p usr/share/icons/hicolor/{16x16/apps,24x24/apps,32x32/apps,48x48/apps,64x64/apps,128x128/apps,256x256/apps}
    for i in "16" "24" "32" "48" "64" "128" "256"; do
        ${SUDO} ln -sf /usr/lib/google-chrome/product_logo_$i.png usr/share/icons/hicolor/${i}x${i}/apps/google-chrome.png
    done
    ${SUDO} rm -rf etc
