name := "lact-libadwaita"
packages := "
lact-libadwaita
"
base_images := "
quay.io/fedora-ostree-desktops/silverblue:41
quay.io/fedora-ostree-desktops/silverblue:42
"
copr_repos := "ilyaz/LACT"
enable_repos := "copr:copr.fedorainfracloud.org:ilyaz:LACT"


import '../sysext.just'

all: default
