FROM baseimage

RUN <<EORUN
set -xeuo pipefail
mv /opt{,.bak}
mkdir /opt
rpm --import https://packages.microsoft.com/keys/microsoft.asc
echo -e '[edge-yum]\nname=edge-yum\nbaseurl=https://packages.microsoft.com/yumrepos/edge/\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc' | tee /etc/yum.repos.d/edge.repo > /dev/null
dnf install -y microsoft-edge-stable
mv /opt/microsoft/msedge /usr/lib/microsoft-edge
ln -sf /usr/lib/microsoft-edge/microsoft-edge /usr/bin/microsoft-edge-stable
mkdir -p usr/share/icons/hicolor/{16x16/apps,24x24/apps,32x32/apps,48x48/apps,64x64/apps,128x128/apps,256x256/apps}
for i in "16" "24" "32" "48" "64" "128" "256"; do
    ln -sf /usr/lib/microsoft-edge/product_logo_$i.png /usr/share/icons/hicolor/${i}x${i}/apps/microsoft-edge.png
done
rm -rf /etc/cron.daily
rmdir /opt/{microsoft,}
mv /opt{.bak,}
dnf clean all
EORUN
