name := "python"
packages := "
libb2
libgomp
mpdecimal
python-pip-wheel
python-unversioned-command
python3
python3-libs
"
base_images := "quay.io/fedora/fedora-coreos:next"

import '../sysext.just'

all: default
