FROM baseimage

RUN <<EORUN
set -xeuo pipefail
url="https://api.github.com/repos/VSCodium/vscodium/releases/latest"
release="$(curl -s "${url}" | jq -r '.tag_name')"
rpmurl="$(curl -s "${url}" | jq -r '.assets[] | select(.name == "codium-'${release}'-el9.x86_64.rpm") | .browser_download_url')"
wget "${rpmurl}"{,.sha256}
sha256sum -c ./*rpm.sha256
dnf install -y ./*.rpm
rm ./*.rpm ./*.rpm.sha256
dnf clean all
EORUN
