FROM baseimage

RUN dnf remove -y nfs-utils-coreos \
    && \
    dnf install -y \
    libvirt-daemon \
    libvirt-daemon-config-network \
    libvirt-daemon-driver-interface \
    libvirt-daemon-driver-network \
    libvirt-daemon-driver-nodedev \
    libvirt-daemon-driver-nwfilter \
    libvirt-daemon-driver-qemu \
    libvirt-daemon-driver-secret \
    libvirt-daemon-driver-storage-core \
    libvirt-dbus \
    netcat \
    qemu-kvm \
    libguestfs \
    libguestfs-xfs \
    qemu-img \
    swtpm \
    && \
    dnf clean all
