name := "libvirtd"
packages := "
guestfs-tools
libguestfs
libguestfs-xfs
libvirt-client
libvirt-daemon
libvirt-daemon-config-network
libvirt-daemon-driver-interface
libvirt-daemon-driver-network
libvirt-daemon-driver-nodedev
libvirt-daemon-driver-nwfilter
libvirt-daemon-driver-qemu
libvirt-daemon-driver-secret
libvirt-daemon-driver-storage-core
libvirt-daemon-driver-storage-disk
libvirt-daemon-driver-storage-iscsi
libvirt-daemon-driver-storage-iscsi-direct
libvirt-daemon-driver-storage-logical
libvirt-daemon-driver-storage-mpath
libvirt-daemon-driver-storage-rbd
libvirt-daemon-driver-storage-scsi
libvirt-dbus
netcat
qemu-img
qemu-kvm
swtpm
virt-install
"
base_images := "
quay.io/fedora/fedora-coreos:stable
"
# Pending nfs-utils packaging rework
pre_commands := "dnf remove -y nfs-utils-coreos"

import '../sysext.just'

all: default

# Fixup netcat/nc as we don't run the alternatives command from scriplets
install-manual:
    #!/bin/bash
    set -euo pipefail
    # set -x

    if [[ "${UID}" == "0" ]]; then
        SUDO=""
    else
        SUDO="sudo"
    fi

    cd rootfs

    ${SUDO} ln -snf netcat usr/bin/nc
