name := "libvirtd"
packages := "
guestfs-tools
libguestfs
libguestfs-xfs
libvirt-client
libvirt-daemon
libvirt-daemon-config-network
libvirt-daemon-driver-interface
libvirt-daemon-driver-network
libvirt-daemon-driver-nodedev
libvirt-daemon-driver-nwfilter
libvirt-daemon-driver-qemu
libvirt-daemon-driver-secret
libvirt-daemon-driver-storage-core
libvirt-dbus
netcat
qemu-img
swtpm
"
base_images := "
quay.io/fedora/fedora-coreos:next
quay.io/fedora-ostree-desktops/kinoite:41
"

import '../sysext.just'

default target: (all target)
