name := "debugtools"
packages := "
gdb-minimal
strace
"
base_images := "
quay.io/fedora/fedora-coreos:next
quay.io/fedora-ostree-desktops/kinoite:41
"

import '../sysext.just'

default target: (all target)
