name := "chromium"
packages := "
chromium
"
# Once removed from the base image?
# fedora-chromium-config
# fedora-chromium-config-kde
base_images := "
quay.io/fedora-ostree-desktops/base-atomic:41 x86_64,aarch64
quay.io/fedora-ostree-desktops/base-atomic:42 x86_64,aarch64
"

import '../sysext.just'

all: default
