name := "kubernetes-1.30"
packages := "
cri-tools1.30
kubernetes1.30
kubernetes1.30-client
kubernetes1.30-kubeadm
kubernetes1.30-systemd
"
exclude_packages := "
cri-tools
"
upholds := "
kubelet.service
"
base_images := "
quay.io/fedora/fedora-coreos:stable x86_64,aarch64
"

import '../sysext.just'

all: default
