FROM baseimage

RUN <<EORUN
set -xeuo pipefail
dnf install -y \
    https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
    https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
dnf install -y \
    mpd \
    mpc \
    mpdris2 \
    ncmpcpp
dnf clean all
EORUN
