name := "mpd"
packages := "
mpd
mpc
mpdris2
ncmpcpp
"
rpm_fusion_repos := "free nonfree"
# quay.io/fedora-ostree-desktops/base-atomic:41 x86_64,aarch64
# quay.io/fedora-ostree-desktops/base-atomic:42 x86_64,aarch64
# quay.io/fedora-ostree-desktops/silverblue:41 x86_64,aarch64
# quay.io/fedora-ostree-desktops/silverblue:42 x86_64,aarch64
# quay.io/fedora-ostree-desktops/kinoite:41 x86_64,aarch64
# quay.io/fedora-ostree-desktops/kinoite:42 x86_64,aarch64
base_images := "
"

import '../sysext.just'

all: default
