name := "mpd"
pre_commands:= "dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm"
enable_repos := "rpmfusion-free"
packages := "
    mpd
    mpc
    mpdris2
    ncmpcpp
"
base_images := "
quay.io/fedora/fedora-coreos:stable
"

import '../sysext.just'

all: default
