FROM baseimage

RUN dnf install -y \
    btop \
    bwm-ng \
    distrobox \
    git-absorb \
    git-delta \
    htop \
    iotop \
    just \
    ripgrep \
    strace \
    zoxide \
    zsh \
    && \
    dnf clean all
