name := "neovim"
packages := "
neovim
tree-sitter-cli
"
dnf_weak_deps := "false"
base_images := "
quay.io/fedora/fedora-coreos:stable
quay.io/fedora-ostree-desktops/silverblue:41
quay.io/fedora-ostree-desktops/kinoite:41
"

import '../sysext.just'

all: default
