name := "incus"
packages := "
incus
incus-client
"
copr_repos := "ganto/lxc4"
version_package := "incus-client"
base_images := "
quay.io/fedora-ostree-desktops/base-atomic:41 x86_64,aarch64
quay.io/fedora-ostree-desktops/base-atomic:42 x86_64,aarch64
"

import '../sysext.just'

all: default

install-manual:
    #!/bin/bash
    set -euo pipefail
    # set -x

    if [[ "${UID}" == "0" ]]; then
        SUDO=""
    else
        SUDO="sudo"
    fi

    cd rootfs

    # Empty out /var
    ${SUDO} rmdir \
        var/cache/{incus,lxc} var/cache \
        var/lib/{incus,lxc,lxcfs} var/lib \
        var/log/incus var/log \
        var
