FROM baseimage

RUN <<EORUN
set -xeuo pipefail
dnf install -y \
    cockpit-files \
    cockpit-networkmanager \
    cockpit-ostree \
    cockpit-podman \
    cockpit-storaged \
    cockpit-system \
    cockpit-ws
dnf clean all
EORUN
