name := "cockpit"
packages := "
cockpit-files
cockpit-networkmanager
cockpit-ostree
cockpit-podman
cockpit-selinux
cockpit-storaged
cockpit-system
cockpit-ws
"
base_images := "
quay.io/fedora/fedora-coreos:stable
"

import '../sysext.just'

all: default
