name := "adobe-source-code-pro-fonts"
packages := "
adobe-source-code-pro-fonts
adobe-source-code-vf-fonts
"
base_images := "
quay.io/fedora-ostree-desktops/base-atomic:41 x86_64,aarch64
quay.io/fedora-ostree-desktops/base-atomic:42 x86_64,aarch64
"

import '../sysext.just'

all: default
